;; (A->B) -> ((B->C) -> ((C->D) -> (A->D)))
(update-ctors m
    (ccs                    Implication)
    (ccs_ante               Implication)
    (ccs_ante_ante         A)
    (ccs_ante_csq          B)
    (ccs_csq_ante          Implication)
    (ccs_csq_ante_ante     B)
    (ccs_csq_ante_csq      C)
    (ccs_csq_csq           Implication)
    (ccs_csq_csq_ante      Implication)
    (ccs_csq_csq_ante_ante C)
    (ccs_csq_csq_ante_csq  D)
    (ccs_csq_csq_csq       Implication)
    (ccs_csq_csq_csq_ante  A)
    (ccs_csq_csq_csq_csq   D))

; If you remove AB, its proof is impossible
; (B->C) -> ((A->B) -> (A->C))
(update-ctors m
    (ccs                Implication)
    (ccs_ante           Implication)
    (ccs_csq            Implication)
    (ccs_csq_ante       Implication)
    (ccs_csq_csq        Implication)
    (ccs_ante_ante      B)
    (ccs_ante_csq       C)
    (ccs_csq_ante_ante  A)
    (ccs_csq_ante_csq   B)
    (ccs_csq_csq_ante   A)
    (ccs_csq_csq_csq    C))

; ((A -> B) -> ((B -> C) -> (A -> C)))
(update-ctors m
    (ccs                Implication)
    (ccs_ante           Implication)
    (ccs_csq            Implication)
    (ccs_csq_ante       Implication)
    (ccs_csq_csq        Implication)
    (ccs_ante_ante      A)
    (ccs_ante_csq       B)
    (ccs_csq_ante_ante  B)
    (ccs_csq_ante_csq   C)
    (ccs_csq_csq_ante   A)
    (ccs_csq_csq_csq    C))
